# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "sd_mod" "vfio-pci" ];
  #gpu passthrough
  boot.initrd.kernelModules = [
    "vfio_pci" "vfio" "vfio_iommu_type1" "vfio_virqfd"
    "amdgpu"
  ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];
  boot.kernelParams = [ "vfio-pci.ids=1002:67df,1002:aaf0" "iommu=pt" "video=efifb:off" "amdgpu.ppfeaturemask=0xffffffff" "amd_iommu=on" ];
  boot.extraModprobeConfig = ''
   options kvm ignore_msrs=1
  '';

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/ed40a5eb-3cb1-44aa-8a6e-f92e5939cc78";
      fsType = "btrfs";
      options = ["ssd" "discard" "noatime"];
    };

  boot.initrd.luks.devices."root".device = "/dev/disk/by-uuid/089c0259-e492-447d-935f-f273b8796d04";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/61BC-7413";
      fsType = "vfat";
    };

  fileSystems."/home/jacob/media" =
    { device = "/dev/disk/by-uuid/8db7f5e7-af75-483c-af2b-2550021ae39d";
      fsType = "btrfs";
      options = ["noatime" "compress=zstd:6" "autodefrag"];
    };

  boot.initrd.luks.devices."media".device = "/dev/disk/by-uuid/7c6ba02b-b3e2-4d72-9e54-6cf124fad7d4";

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp5s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
